# Generated by Django 4.2.5 on 2023-09-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='seat',
        ),
        migrations.AddField(
            model_name='concert',
            name='seat',
            field=models.ManyToManyField(to='booking.seat'),
        ),
    ]
