# Generated by Django 4.2.5 on 2023-09-15 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_concert_seat_concert_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='paid_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='no_of_seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_type',
            field=models.CharField(choices=[('', 'Select'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
